### ISSUE TITLE
Flickering when removing a previous page's ViewController 

### ISSUE THREAD

**Issue by 5b5** [stefanceriu/SCPageViewController#28]
Thanks for your work! Works almost entirely like a charm, except one thing...
when removing the previous ViewController (e.g. i'm on page with index 1 and removing page 0) with deletePagesAtIndexes:animated:completion: the previous page (page 0) is shown for the fraction of a second which looks like a weird flickering.
The effect can be seen when setting a breakpoint inside the dispatch_group_notify-Block at the end of the method.
The effect occurs at least with SCSlidingPageLayouter and SCParallaxPageLayouter.

**Comment by stefanceriu** [comment]
Hey, sorry for the late.
Although I couldn't really reproduce it I think I figure out what went wrong. 
I pushed a fix to develop if you would be so kind to give it a go.

**Comment by 5b5** [comment]
Thanks for your efforts! Going to test today...

**Comment by 5b5** [comment]
OK, that was hard but I have a result:
I rewrote the whole surrounding logic in the meanwhile and recognized i couldn't reproduce the bug on my own in my current version. So i checked out the old version and there it was again. There was no difference between master and develop, so your changes didn't fix at least this issue.
After checking my changes between the current and old version of my code i recognized that i was using animated:false in the old version and now i'm using animated:true (which should make no difference for me, as the removed ViewController is not visible at the time of removal)

So i found out that the problem only occurs when using deletePagesAtIndexes WITHOUT animation! (even in my new version, i checked!) Hope that helps you to reproduce/fix the problem.

**Comment by stefanceriu** [comment]
Hey, sorry for taking waay way to long to get back to this. I finally managed to have a proper look at it, reproduce it and fix it .. I think :)
Thank you for raising the issue to begin with and for testing it out.
